### ISSUE TITLE
本项目描述的统一

### ISSUE THREAD

**Issue by mzlogin** [vim-china/awesome-vimers#4]
项目的描述当前为 `国内比较厉害的 Vim 用户清单`，README 里写的是 `在这里，将列出一些由国内用户开发出来的插件，欢迎大家推荐`，在 issues 项目里对本项目的描述是 `推荐一些不错的国人开发的插件至 awesome-vimers 仓库`，几处的描述不太一致，需要统一一下。

如果是以插件为主体的话，awesome-vimers 这个项目名字可能也需要修改一下。

**Comment by wsdjeg** [comment]
仓库名字不该的情况下，有什么好的建议吗？URL的修改会导致很多问题，这个一般尽量需要规避

**Comment by mzlogin** [comment]
仓库名字不改也可以，反正咱们是 vim-china，那本项目可以作为列出写了一些实用 Vim 插件的国人用户，以及其对应插件作品的地方，以 user 作为线索。

这样的话，修改 *项目描述* 一项，与其它两处一致即可，比如改为 `国内比较有影响力的 Vim 用户及其插件作品`。

**Comment by wsdjeg** [comment]
可以，欢迎提交PR

**Comment by mzlogin** [comment]
![image](https://user-images.githubusercontent.com/1646590/38844075-8027743e-4224-11e8-9188-52b99333b4e8.png)

这块 PR 不了……你直接改一下好了 😆
